### ISSUE TITLE
endless loop at runtime for heightForRowAtIndexPath:

### ISSUE THREAD

**Issue by aphex3k** [DylanVann/DatePickerCell#10]
if I run this code from the documentation inside `override func tableView(tableView: UITableView, heightForRowAtIndexPath indexPath: NSIndexPath) -> CGFloat` I get stuck in an endless loop:

```
let cell = self.tableView(tableView, cellForRowAtIndexPath: indexPath)
if (cell.isKindOfClass(DatePickerCell)) {
    return (cell as! DatePickerCell).datePickerHeight()
}
```

I guess prior to returning from `cellForRowAtIndexPath:` the tableView calls `heightForRowAtIndexPath:` itself

It happens when using `dequeueReusableCellWithIdentifier` in `cellForRowAtIndexPath:`. A workaround would be to instantiate the cells instance like you did in the example and keep a reference to it...

**Comment by DylanVann** [comment]
hm... That would be up to the implementation of `cellForRowAtIndexPath`. I don't think `cellForRowAtIndexPath` should usually need the height, or at least it could fetch the height using a different method than calling `heightForRowAtIndexPath`.
