### ISSUE TITLE
Different behaviour on iOS 8.3 and iOS 10.2

### ISSUE THREAD

**Issue by SergeHaddad** [DylanVann/DatePickerCell#20]
I added table view cells in a tableviewcontroller and changed their class to DatePickerCell. Added the needed tableview functions, but i'm getting the right behaviour on iOS 10.2 on Simulator, but weird results on iPhone 5S running iOS 8.3 where clicking on a cell expands another one. Why is that?

**Comment by DylanVann** [comment]
I can't reproduce any issues in the example on iOS 8.3. I'll look into adding an example with multiple cells.

**Comment by DylanVann** [comment]
![looks_fine_to_me](https://cloud.githubusercontent.com/assets/1537615/25694318/1b0a115c-307c-11e7-9767-b93b3b9471b4.gif)

**Comment by Jamie-Ling** [comment]
I also encountered this problem, please help me

**Comment by DylanVann** [comment]
Can you show some code to replicate the issue?

**Comment by Jamie-Ling** [comment]
![Uploading GIF.gif…]()

**Comment by Jamie-Ling-iOS** [comment]
![gif 1](https://cloud.githubusercontent.com/assets/11729845/25795612/b449c5f8-3408-11e7-897a-3cc2bf4ce354.gif)

**Comment by Jamie-Ling-iOS** [comment]
iOS9 and iOS10 is all right。 only happen in iOS8
Looks like they're moving up, when open this page, the log :

2017-05-08 16:14:40.730 XXX[15067:706575] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fc34a2a29a0 UILabel:0x7fc34a293720.height == 44>",
    "<NSLayoutConstraint:0x7fc34a2b4bc0 UILabel:0x7fc34a293720.top == UITableViewCellContentView:0x7fc34a2788f0.top>",
    "<NSLayoutConstraint:0x7fc34a2a0320 UIView:0x7fc34a28c930.top == UILabel:0x7fc34a293720.bottom>",
    "<NSLayoutConstraint:0x7fc34a278f40 UIView:0x7fc34a28c930.bottom == UITableViewCellContentView:0x7fc34a2788f0.bottom + 1>",
    "<NSLayoutConstraint:0x7fc34a668000 UITableViewCellContentView:0x7fc34a2788f0.height == 42.6667>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fc34a2a0320 UIView:0x7fc34a28c930.top == UILabel:0x7fc34a293720.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2017-05-08 16:14:40.745 JD-App[15067:706575] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fc34a49c810 UILabel:0x7fc34a498780.height == 44>",
    "<NSLayoutConstraint:0x7fc34a49c860 UILabel:0x7fc34a498780.top == UITableViewCellContentView:0x7fc34a49af70.top>",
    "<NSLayoutConstraint:0x7fc34a49dca0 UIView:0x7fc34a499b70.top == UILabel:0x7fc34a498780.bottom>",
    "<NSLayoutConstraint:0x7fc34a49dcf0 UIView:0x7fc34a499b70.bottom == UITableViewCellContentView:0x7fc34a49af70.bottom + 1>",
    "<NSLayoutConstraint:0x7fc34a6a1710 UITableViewCellContentView:0x7fc34a49af70.height == 42.6667>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fc34a49dca0 UIView:0x7fc34a499b70.top == UILabel:0x7fc34a498780.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by Jamie-Ling-iOS** [comment]
Hi, @DylanVann , The problem is solved by adding method : estimatedHeightForRowAt.
Thank you very much

**Comment by DylanVann** [comment]
@Jamie-Ling-iOS Problem solved 🎊 . Great!
