### ISSUE TITLE
Fonts?

### ISSUE THREAD

**Issue by daviddelmonte** [DylanVann/DatePickerCell#21]
Is there any way to change fonts to the same as my tableView cells? Thanks

**Comment by DylanVann** [comment]
Hmm... I'll look into this. I imagine most uses of this are people making
things that they want to look like apps made by apple, like calendar.

In the case that you are using a different font for the rest of your cells
though I can see how this would look weird.

**Comment by daviddelmonte** [comment]
I prefer your control but I found a solution using [PIDatePicker](https://github.com/prolificinteractive/PIDatePicker)
