### ISSUE TITLE
Multiple Sections and rows

### ISSUE THREAD

**Issue by poonam-more** [DylanVann/DatePickerCell#3]
How can we do with multiple sections and multiple rows in tableview?

**Comment by DylanVann** [comment]
It depends on your use case and how you like to build your interfaces. 

I like to build static TableViews in code, like how it's done in the example. In the example each column in the array is a section, and each row is a cell. You could construct a different TableView like this:

``` swift
cells = [
    // Start of first section.
    [
        section1Row1,
        section1Row2,
        section1Row3,
    ],
    //Start of second section.
    [
        section2Row1,
        section2Row2,
    ],
];
```

There are other ways to build your TableView: dynamically with code, or with Interface Builder. This isn't really a DatePickerCell issue though.
