### ISSUE TITLE
Release v1.0.3 to CocoaPods

### ISSUE THREAD

**Issue by ColinEberhardt** [DylanVann/DatePickerCell#8]
This is a useful little lib! I'd like to use it within an application I am building for an up-coming tutorial on raywenderlich.com - so hopefully it will give this project a bit more exposure.

I'm using iOS9, so could really do with having v1.0.3 on CocoaPods. Thanks :-)

**Comment by ColinEberhardt** [comment]
**bump**

sorry to be a pain, but I am writing the article next week and would really love to use this code :-)

**Comment by DylanVann** [comment]
It's awesome that you're writing an article using this. I'm excited to see it :)

I got the earlier comment. I just moved and started a new job so things have been hectic the past week. I'll push the updates before Friday.

**Comment by ColinEberhardt** [comment]
Thanks - much appreciated. And good luck with your move / new job :-)

**Comment by DylanVann** [comment]
Let me know if you have any issues with it
