### ISSUE TITLE
No pods?

### ISSUE THREAD

**Issue by ElectrumDevelopment** [DylanVann/DatePickerCell#9]
Any way to do it without cocao pods?

**Comment by aphex3k** [comment]
I guess you just copy the class files into your project? What is your problem exactly?

**Comment by ElectrumDevelopment** [comment]
"Cannot load underlying module for "datepickercell"

**Comment by DylanVann** [comment]
Just copy DatePickerCell.swift into your project.

**Comment by ElectrumDevelopment** [comment]
Sweet thanks! Got it to work! Im using it with a uitableview and when the picker is "closed" it still shows the rest of the empty table, blocking the content under it

**Comment by DylanVann** [comment]
Screenshot?

**Comment by ElectrumDevelopment** [comment]
http://imgur.com/a/fHZIh

In the first screenshot, there was supposed to be something under there

**Comment by DylanVann** [comment]
It looks like the DatePicker isn't visibly blocking it. Those cells just aren't loading. Probably an issue with `cellForRowAtIndexPath`.
